# Generated by Django 3.1.2 on 2020-12-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0002_note_photo'),
        ('lmn', '0008_auto_20201118_1254'),
    ]

    operations = [
    ]
